version: "2"
services:
  jenkins:
    image: cobrijani/jenkins
    environment:
      FORKED_ORG: "${FORKED_ORG}"
      EXTERNAL_IP: "${EXTERNAL_IP}"
      JENKINS_OPTS: "--prefix=/jenkins"
    ports:
      - "50000:50000"
      - "8080:8080"
    networks:
      - proxy
    volumes:
      - jenkins_home:/var/jenkins_home
      - ~/jenkins_root:/root/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - artifactory
  artifactory:
    build:
      context: .
      dockerfile: Dockerfile-artifactory
    ports:
      - "8081:8081"
    networks:
      - proxy


networks:
  proxy:
    external:
      name: proxy
volumes:
  jenkins_home:
    external:
      name: jenkins_home
